config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  devise_for :admins, skip: [:registrations, :sessions]
  devise_for :parents, skip: :sessions, :controllers => {:registrations => "parent_registrations"}
  devise_for :tutors, skip: :sessions, :controllers => {:registrations => "tutor_registrations"}

  root :to => "pages#index"
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  get "groups/update_host", as: "update_host"
  resources :groups
  resources :children
  patch "children/:id/drop" => "children#drop", as: :drop

  resources :admins
  resources :parents
  get "parents/:id/payments" => "parents#payments", as: :parent_payments
  get "parents/:id/add_payment_info" => "parents#add_payment_info", as: :parent_add_payment_info
  post "parents/:id/store_card" => "parents#store_card", as: :parent_store_card
  resources :tutors
  get "tutors/:id/lessons" => "tutors#lessons", as: :tutor_lessons

  get "lessons/update_attendance", as: "update_attendance"
  resources :lessons

  get "pages/index" => "pages#index"
  get "pages/parents" => "pages#parents"
  get "pages/tutors" => "pages#tutors"
  get "pages/kidscorner" => "pages#kidscorner"
  get "pages/contact" => "pages#contact"
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :lesson
  belongs_to :child
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :group, optional: true
  belongs_to :parent
end

app/models/group.rb
class Group < ApplicationRecord
	validates :tutor, presence: true
	# validates :schedule, presence: true
	belongs_to :tutor
	belongs_to :host, class_name: "Parent"
	attr_accessor :children
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :group, presence: true
  belongs_to :group
  attr_accessor :attendance
end

app/models/parent.rb
class Parent < User
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :parent
  attr_accessor :price, :num_credits
end

app/models/tutor.rb
class Tutor < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController

	def index
		require_user!(admin_logged_in?)
		@children = Child.all.order(:parent_id, :name)
	end

	def show
		@child = Child.find(params[:id])
		require_user!(admin_logged_in? || (current_user == @child.parent && !@child.parent.customer_id.nil?))
		@attendance = Attendance.where(child: @child).sort do |a, b|
			b.lesson.datetime <=> a.lesson.datetime
		end
	end

	def new
		require_user!(admin_logged_in? || (parent_logged_in? && !current_parent.customer_id.nil?))
		@child = Child.new
	end

	def create
		@child = Child.new(child_params)
		@child.parent = current_parent

		if @child.save
			Activity.create!({activity_type: "ADD_CHILD", user: @child.parent, object: @child.id})
			flash[:notice] = "New child has been added successfully!"
			redirect_to child_path(@child)
		else
			flash.now[:alert] = "Not able to add child!"
			render "new"
		end
	end

	def edit
		@child = Child.find(params[:id])
		require_user!(admin_logged_in? || (current_user == @child.parent && !@child.parent.customer_id.nil?))
	end

	def update
		@child = Child.find(params[:id])

		if @child.update(child_params)
			flash[:notice] = @child.name + "'s profile has been successfully updated!"
			redirect_to child_path(@child)
		else
			flash.now[:alert] = "Not able to update " + @child.name + "'s profile!"
			render "edit"
		end
	end

	def drop
		@child = Child.find(params[:id])
		require_user!(admin_logged_in? || (current_user == @child.parent && !@child.parent.customer_id.nil?))

		if @child.update_attribute(:group_id, nil)
			flash[:notice] = @child.name + " has successfully dropped his/her group!"
		else
			flash.now[:alert] = "Unable to drop out of " + @child.name + "'s group!"
		end
		redirect_to child_path(@child)
	end

	private

	def child_params
		params.require(:child).permit(:name, :age, :grade, :skill, :parent)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :authenticate_user!
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/children/edit.html.erb
<div class="page-header">
<h2>Edit <%= @child.name %>'s Profile</h2>
<ul class="actions">
	<% if admin_logged_in? %>
		<li><%= link_to "Back", child_path(@child), class: "btn btn-primary" %></li>
	<% end %>
	<% if parent_logged_in? %>
		<li><%= link_to "Back", child_path(@child), class: "btn btn-primary" %></li>
	<% end %>
</ul>
</div>

<%= simple_form_for(@child) do |f| %>
	<%= f.input :name %>
	<%= f.input :grade, collection: ["Pre-K", "Kindergarten"] + (1..12).to_a + ["Post High School"] %>
	<%= f.input :skill, collection: ["Beginner", "Intermediate", "Advanced"] %>

	<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/children/index.html.erb
<div class="page-header">
<h2>Children</h2>
<ul class="actions">
	<li><%= link_to "Back", admin_url(current_admin), class: "btn btn-primary" %></li>
</ul>
</div>

<div class="table-responsive">
<table class="table table-bordered">
	<thead>
		<td>Name</td>
		<td>Parent</td>
		<td>Group</td>
		<td>Tutor</td>
		<td></td>
	</thead>
	<% @children.each do |child| %>
		<tr class=<%= child.group_id == nil ? "danger" : "" %>>
			<td><%= child.name %></td>
			<td><%= link_to child.parent.name, parent_path(child.parent) %></td>
			<td><%= child.group.nil? ? "Unassigned" : "Group: " + child.group.name %></td>
			<td><%= child.group.nil? ? "N/A" : (link_to child.group.tutor.name, tutor_path(child.group.tutor)) %></td>
			<td><%= link_to "View", child_path(child), class: "btn btn-primary" %></td>
		</tr>
	<% end %>
</table>
</div>

app/views/children/new.html.erb
<div class="page-header">
<h2>Add Child</h2>
<ul class="actions">
	<% if admin_logged_in? %>
		<li><%= link_to "Back", children_path, class: "btn btn-primary" %></li>
	<% end %>
	<% if parent_logged_in? %>
		<li><%= link_to "Back", parent_path(current_parent), class: "btn btn-primary" %></li>
	<% end %>
</ul>
</div>

<%= simple_form_for(@child) do |f| %>
	<%= f.input :name %>
	<%= f.input :grade, collection: ["Pre-K", "Kindergarten"] + (1..12).to_a + ["Post High School"] %>
	<%= f.input :skill, collection: ["Beginner", "Intermediate", "Advanced"] %>

	<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/children/show.html.erb
<div class="page-header">
<h2><%= @child.name %>'s Profile</h2>
<ul class="actions">
	<% if admin_logged_in? %>
		<li><%= link_to "Back", children_path, class: "btn btn-primary" %></li>
	<% end %>
	<% if parent_logged_in? %>
		<li><%= link_to "Back", parent_path(@child.parent), class: "btn btn-primary" %></li>
	<% end %>
	<li><%= link_to "Edit", edit_child_path(@child), class: "btn btn-warning" %></li>
</ul>
</div>

<p>Parent: <%= link_to @child.parent.name, parent_path(@child.parent) %></p>
<p>Grade: <%= @child.grade %></p>
<p>Skill: <%= @child.skill %></p>

<% if @child.group.nil? %>
	<p>Group Unassigned</p>
<% else %>
	<div class="well">
		<p>Group: <%= @child.group.name %> </p>
		<p>Tutor: <%= link_to @child.group.tutor.name, tutor_path(@child.group.tutor) %></p>
		<%= link_to "Drop", drop_path, class: "btn btn-danger", method: :patch %></p>
	</div>
<% end %>

<h3>Attendence History</h3>
<% @attendance.each do |a| %>
<div class="panel panel-<%= a.present ? 'success' : 'danger' %>">
	<div class="panel-heading">Lesson #<%= a.lesson.id %></div>
	<div class="panel-body">
		<p><%= a.lesson.datetime.strftime("%A %b %d, %Y %l:%M %p") %></p>
		<p><%= a.lesson.group.name %></p>
		<p><%= a.lesson.notes %></p>
	</div>
</div>
<% end %>