config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  devise_for :admins, skip: [:registrations, :sessions]
  devise_for :parents, skip: :sessions, :controllers => {:registrations => "parent_registrations"}
  devise_for :tutors, skip: :sessions, :controllers => {:registrations => "tutor_registrations"}

  root :to => "pages#index"
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  get "groups/update_host", as: "update_host"
  resources :groups
  resources :children
  patch "children/:id/drop" => "children#drop", as: :drop

  resources :admins
  resources :parents
  get "parents/:id/payments" => "parents#payments", as: :parent_payments
  get "parents/:id/add_payment_info" => "parents#add_payment_info", as: :parent_add_payment_info
  post "parents/:id/store_card" => "parents#store_card", as: :parent_store_card
  resources :tutors
  get "tutors/:id/lessons" => "tutors#lessons", as: :tutor_lessons

  get "lessons/update_attendance", as: "update_attendance"
  resources :lessons

  get "pages/index" => "pages#index"
  get "pages/parents" => "pages#parents"
  get "pages/tutors" => "pages#tutors"
  get "pages/kidscorner" => "pages#kidscorner"
  get "pages/contact" => "pages#contact"
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :lesson
  belongs_to :child
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :group, optional: true
  belongs_to :parent
end

app/models/group.rb
class Group < ApplicationRecord
	validates :tutor, presence: true
	# validates :schedule, presence: true
	belongs_to :tutor
	belongs_to :host, class_name: "Parent"
	attr_accessor :children
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :group, presence: true
  belongs_to :group
  attr_accessor :attendance
end

app/models/parent.rb
class Parent < User
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :parent
  attr_accessor :price, :num_credits
end

app/models/tutor.rb
class Tutor < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/admins/show.html.erb
<div class="page-header">
<h2>Admin Portal</h2>
<ul class="actions">
	<li><%= link_to "Tutors", tutors_path, class: "btn btn-primary" %></li>
	<li><%= link_to "Parents", parents_path, class: "btn btn-primary" %></li>
	<li><%= link_to "Children", children_path, class: "btn btn-primary" %></li>
	<li><%= link_to "Groups", groups_path, class: "btn btn-primary" %></li>
</ul>
</div>

<h3>Activity Log</h3>
<div class="table-responsive">
<table class="table table-bordered">
	<thead>
		<td>Date and Time</td>
		<td>Activity</td>
	</thead>
	<% @activities.each do |activity| %>
		<tr>
			<td><%= activity.created_at.strftime("%m/%d/%Y %l:%M %p") %></td>
			<td><%= activity_description(activity) %></td>
		</tr>
	<% end %>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NAS Chess Academy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= tag :meta, :name => "stripe-key", :content => Rails.configuration.stripe[:publishable_key] %>
  </head>

  <body>
    <% if user_signed_in? %>
    Signed in as <%= current_user.email %> (<%= current_user.class.name %>)
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <% else %>
    Not signed in.
    <% end %>  
    <div class="container">
  	<% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>">
  		  <%= message %>
      </div>
  	<% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/_footer.html.erb
<div class="container-fluid footer" align="center">
	<div class="row">
		<div class="col-sm-6 col-xs-12">
			<div class="col-sm-6 col-xs-6">
				<p><%= link_to "HOME", root_path %></p>
				<p><%= link_to "KIDS CORNER", pages_kidscorner_path %></p>
				<p><%= link_to "PARENTS", pages_parents_path %></p>
				<p><%= link_to "TUTORS", pages_tutors_path %></p>
				<p><%= link_to "CONTACT", pages_contact_path %></p>
				<p><%= link_to "DASHBOARD", new_user_session_path %></p>
			</div>
		    <div class="col-sm-6 col-xs-6">
		    	<p><%= link_to "HOW IT WORKS", pages_parents_path(anchor: "howItWorks") %></p>
		    	<p><%= link_to "REGISTRATION", pages_parents_path(anchor: "registration") %></p>
		    	<p><%= link_to "MAKE A PAYMENT", pages_parents_path(anchor: "payment") %></p>
			</div>
		</div>
		<div class="col-sm-6 col-xs-12">
			<div class="col-sm-6 col-xs-6 vertical-divider">
				<%= link_to pages_parents_path(anchor: "registration") do %>
				    <h2>Parents</h2>
				    <%= image_tag("/img/RegisterHere.png", class: "img-responsive") %>
				<% end %>
			</div>
			<div class="col-sm-6 col-xs-6">
				<%= link_to pages_tutors_path do %>
				    <h2>Tutors</h2>
				    <%= image_tag("/img/ApplyHere.png", class: "img-responsive") %>
				<% end %>
		    </div>
	    </div>
	</div>
	<hr>
	<p>All Rights Reserved &copy; 2017 NAS Chess Academy, LLC.</p>
</div>

app/views/pages/_navbar.html.erb
<div class="container-fluid navbar">
	<%= link_to image_tag("/img/Logo.png", class: "img-responsive"), root_path %>
	<ul class="nav navbar-nav navbar-right">
	    <li><%= link_to "HOME", root_path, class: (index == 0) ? "active" : "" %></li>
	    <li><%= link_to "KIDS CORNER", pages_kidscorner_path, class: (index == 1) ? "active" : "" %></li>
	    <li><%= link_to "PARENTS", pages_parents_path, class: (index == 2) ? "active" : "" %></li>
	    <li><%= link_to "TUTORS", pages_tutors_path, class: (index == 3) ? "active" : "" %></li>
	    <li><%= link_to "CONTACT", pages_contact_path, class: (index == 4) ? "active" : "" %></li>
	    <li><%= link_to "DASHBOARD", new_user_session_path, class: (index == 5) ? "active" : "" %></li>
	</ul>
</div>

app/views/pages/contact.html.erb
<div class="container container-body">
	<%= render partial: "navbar", locals: {index: 4} %>
	<div class="container container-main">
		<div class="container-fluid container-type-2" align="center">
			<div class="row">
				<div class="col-sm-6">
					<h2>WE'D LOVE TO HEAR FROM YOU!</h2>
					<script type="text/javascript" src="https://form.jotform.us/jsform/71354297650157"></script>
				</div>
				<div class="col-sm-6">
					<h2>ADDITIONAL INFORMATION</h2>
					<p>Please bear with us while we create our social media presence!</p>
					<img class="img-responsive" src="/img/SM_Primer.png" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); height: 300px; width: 300px;"></img>
				</div>
			</div>
		</div>
        <%= render partial: "footer" %>
	</div>
</div>

app/views/pages/index.html.erb
<div class="container container-body">
	<%= render partial: "navbar", locals: {index: 0} %>
	<div class="container container-main container-main-padded">
		<div class="container-fluid container-type-1">
			<div class="row">
				<div class="col-sm-7">
					<div id="myCarousel" class="carousel slide" data-ride="carousel">
					    <!-- Indicators -->
					    <ol class="carousel-indicators">
					      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
					      <li data-target="#myCarousel" data-slide-to="1"></li>
					      <li data-target="#myCarousel" data-slide-to="2"></li>
					    </ol>

					    <!-- Wrapper for slides -->
					    <div class="carousel-inner">
					      <div class="item active">
					        <img src="/img/Stock1.jpg" alt="NAS Chess 1" style="width:100%;">
					      </div>

					      <div class="item">
					        <img src="/img/Stock2.jpg" alt="NAS Chess 2" style="width:100%;">
					      </div>
					    
					      <div class="item">
					        <img src="/img/Stock3.jpg" alt="NAS Chess 3" style="width:100%;">
					      </div>
					    </div>

					    <!-- Left and right controls -->
					    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
					      <span class="glyphicon glyphicon-chevron-left"></span>
					      <span class="sr-only">Previous</span>
					    </a>
					    <a class="right carousel-control" href="#myCarousel" data-slide="next">
					      <span class="glyphicon glyphicon-chevron-right"></span>
					      <span class="sr-only">Next</span>
					    </a>
				  	</div>
				</div>
				<div class="col-sm-5">
					<h1>Welcome to NAS Chess!</h1>
					<p>At NAS Chess Academy our mission is to create an educational and challenging environment for children to learn the greatest strategy game known to man... while having lots of fun! The exciting game of Chess engages children and builds important skills, including: spatial thinking, problem solving, analytical thinking, and emotional maturity. Exposing your child to Chess at an early age may help them develop a healthy appreciation of strategy, competition, and discipline. So, get started today!</p>
				</div>
			</div>
		</div>
		<br>
		<div class="container-fluid container-type-2">
			<div class="row panel-group">
				<div class="col-sm-4 panel-col" id="whoWeAre">
					<div class="panel panel-default">
						<div class="panel-heading">
							<img src="img/King.png">
							<h2>WHO WE ARE</h2>
						</div>
						<div class="panel-body">
							<p>We have a team of hand-picked tutors who not only love Chess, but have been selected because of their ability to teach young children in a passionate, encouraging, and charismatic way, ensuring that your child will learn Chess and have fun along the way.</p>
						</div>
					</div>
				</div>
				<div class="col-sm-4 panel-col" id="whoWeServe">
					<div class="panel panel-default">
						<div class="panel-heading">
							<img src="img/Queen.png">
							<h2>WHO WE SERVE</h2>
						</div>
						<div class="panel-body">
							<p>NAS Chess Academy is for children in Pre-K to 8th grade. Currently, we operate in Bergen County, NJ. <br>
							If you live outside this region and are interested in enrolling your child, contact us to see if we can spread the joy of Chess in your area!</p>
						</div>
					</div>
				</div>
				<div class="col-sm-4 panel-col" id="whatWeDo">
					<div class="panel panel-default">
						<div class="panel-heading">
							<img src="img/Knight.png">
							<h2>WHAT WE DO</h2>
						</div>
						<div class="panel-body">
							<p>Instead of you coming to us, we’ll come to you! We match a group of students with one of our tutors who will come to a designated location once a week to provide Chess lessons to your child and his or her friends.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<%= render partial: "footer" %>
	</div>
</div>

<script>
$(document).ready(function() {
	$(window).resize(function() {
		var max_height = 0;
		$('.panel-col').each(function () {
			max_height = ($(this).height() > max_height ? $(this).height() : max_height); 
		});
		$('.panel-col').height(max_height);
	});
	$(window).resize();
});
</script>

app/views/pages/kidscorner.html.erb
<div class="container container-body">
	<%= render partial: "navbar", locals: {index: 1} %>
	<div class="container container-main">
		<div class="container-fluid container-type-2">
			<h1>Daily Chess Puzzle</h1>
			<div class="row">
				<div class="col-sm-2">
				</div>
				<div class="col-sm-8">
					<p>Solve the Chess Puzzle below. There are three difficulty levels you can try. Come back every day to try a new set of puzzles!</p>
					<div style="width: 100%; text-align: center;">
					<iframe width="310" scrolling="no" height="341" frameborder="0" src="http://www.shredderchess.com/online/playshredder/
gdailytactics.php?mylang=en&mysize=32"></iframe>
					</div>
				</div>
				<div class="col-sm-2">
				</div>
			</div>
		</div>
		<%= render partial: "footer" %>
	</div>
</div>

app/views/pages/parents.html.erb
<div class="container container-body">
	<%= render partial: "navbar", locals: {index: 2} %>
	<div class="container container-main">
		<div class="container-fluid container-type-2">
			<div class="row">
				<div class="col-sm-6">
					<h2>WHAT WOULD YOU LIKE TO DO?</h2>
					<ul class="special-bullets">
						<a href="#howItWorks">
							<li style="background-image: url('/img/bulletKing.png');">Learn How It Works</li>
						</a>
						<a href="#registration">
							<li style="background-image: url('/img/bulletBishop.png');">Registration</li>
						</a>
						<a href="#payment">
							<li style="background-image: url('/img/bulletKnight.png');">Make a Payment</li>
						</a>
					</ul>
				</div>
				<div class="col-sm-6">
					<img class="img-responsive" src="/img/Stock4.jpg" style="border: 1px solid #002060">
				</div>
			</div>
		</div>
		<div class="container-fluid container-type-1" id="howItWorks">
			<h2>How It Works<a href="#"><i class="fa fa-angle-up"></i></a></h2>
			<p>Our Chess tutoring services are for children in Pre-K through 8th grade. Currently, we operate in Bergen County, NJ. Once you register your child, we will work with you to match your child up with other children in your area who are in a similar age group - ideally in a group of four. The tutoring services take place at one of the parents' houses.</p>
			<br>
			<p>Next, we match the group up with one of our hand-selected tutors who not only love Chess, but have also been chosen because of their ability to teach young children in a captivating and enticing manner, ensuring that your child will learn Chess and have a lot of fun in the process!</p>
			<br>
			<p>Finally, we select a start date and time slot that works for the parents and the tutor, and let the fun begin!</p>
		</div>
		<div class="container-fluid container-type-4" id="registration">
			<h2>Registration<a href="#"><i class="fa fa-angle-up"></i></a></h2>
			<p>Fill out the form below to enroll your children today!</p>
			<script type="text/javascript" src="https://form.jotform.us/jsform/71347108950153"></script>
		</div>
		<div class="container-fluid container-type-2" id="payment">
			<h2>Make a Payment<a href="#"><i class="fa fa-angle-up"></i></a></h2>

			<div class="row">
				<div class="col-sm-1">
				</div>
				<div class="col-sm-4">
					<p style="text-decoration: underline;">4+ students per class:</p>
<!-- START: CCV15 PAYPAL BUTTON -->

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="36GV7CVEXV23Y">
<input type="hidden" name="on0" value="How many classes?">
<div class="form-group">
<label for="sel1">How many classes?</label>
<select name="os0" class="form-control" id="sel1">
	<option value="Ten (10) Classes - Super Value Pack!">Ten (10) Classes - Super Value Pack! $135.00 USD</option>
	<option value="Five (5) Classes - Value Pack!">Five (5) Classes - Value Pack! $70.00 USD</option>
	<option value="Single (1) Class">Single (1) Class $15.00 USD</option>
</select>
</div>
<input type="hidden" name="on1" value="Email Address:">
<div class="form-group">
<label for="email1">Email Address:</label>
<input type="text" name="os1" maxlength="200" class="form-control" id="email1">
</div>
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

<!-- END: CCV15 PAYPAL BUTTON -->					
				</div>
				<div class="col-sm-2">
				</div>
				<div class="col-sm-4">
					<p style="text-decoration: underline;">3 students per class:</p>
<!-- START: CCV20 PAYPAL BUTTON -->

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="7LGJBZR5M636A">
<input type="hidden" name="on0" value="How many classes?">
<div class="form-group">
<label for="sel2">How many classes?</label>
<select name="os0" class="form-control" id="sel2">
	<option value="Ten (10) Classes - Super Value Pack!">Ten (10) Classes - Super Value Pack! $180.00 USD</option>
	<option value="Five (5) Classes - Value Pack!">Five (5) Classes - Value Pack! $95.00 USD</option>
	<option value="Single (1) Class">Single (1) Class $20.00 USD</option>
</select>
</div>
<input type="hidden" name="on1" value="Email Address:">
<div class="form-group">
<label for="email2">Email Address:</label>
<input type="text" name="os1" maxlength="200" class="form-control" id="email2">
</div>
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

<!-- END: CCV20 PAYPAL BUTTON -->

				</div>
				<div class="col-sm-1">
				</div>
			</div>

		<p><br>If you prefer to pay by check, please mail a check to:<br><br>
		NAS Chess Academy<br>
		191 Main Street, Suite D3<br>
		Farmington, CT 06032</p>
		
	    </div>
	    <%= render partial: "footer" %>
    </div>
</div>

app/views/pages/tutors.html.erb
<div class="container container-body">
	<%= render partial: "navbar", locals: {index: 3} %>
	<div class="container container-main">
		<div class="container-fluid container-type-2">
			<div class="row">
				<div class="col-sm-6">
					<h2>SO YOU WANNA BE A TUTOR?</h2>
					<h3>...here's what we're looking for!</h3>
					<br>
					<p style="font-size: 26px;">Our tutors are carefully selected to have two main qualities: a passion for Chess and a knack for teaching young children in a patient, encouraging, and charismatic way.</p>
				</div>
				<div class="col-sm-6">
					<img class="img-responsive" src="/img/Stock7.jpg"></img>
				</div>
			</div>
			<p>To be a tutor, you must:</p>
			<ul>
				<li><p>Know how to play Chess (You don't have to be an expert! You will be teaching our pre-set curriculum)</p></li>
				<li><p>Be very good with young children</p></li>
				<li><p>Be very responsible and organized</p></li>
				<li><p>Have a reliable means of transportation</p></li>
			</ul>
			<p>If you are interested and meet these requirements, fill out the application below!</p>
		</div>
		<div class="container-fluid container-type-4">
			<h2>Apply Here<a href="#"><i class="fa fa-angle-up"></i></a></h2>
			<p>Fill out the form below to apply today!</p>
			<script type="text/javascript" src="https://form.jotform.com/jsform/71354285250150"></script>

		</div>
		<%= render partial: "footer" %>
	</div>
</div>