config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  devise_for :admins, skip: [:registrations, :sessions]
  devise_for :parents, skip: :sessions, :controllers => {:registrations => "parent_registrations"}
  devise_for :tutors, skip: :sessions, :controllers => {:registrations => "tutor_registrations"}

  root :to => "pages#index"
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  get "groups/update_host", as: "update_host"
  resources :groups
  resources :children
  patch "children/:id/drop" => "children#drop", as: :drop

  resources :admins
  resources :parents
  get "parents/:id/payments" => "parents#payments", as: :parent_payments
  get "parents/:id/add_payment_info" => "parents#add_payment_info", as: :parent_add_payment_info
  post "parents/:id/store_card" => "parents#store_card", as: :parent_store_card
  resources :tutors
  get "tutors/:id/lessons" => "tutors#lessons", as: :tutor_lessons

  get "lessons/update_attendance", as: "update_attendance"
  resources :lessons

  get "pages/index" => "pages#index"
  get "pages/parents" => "pages#parents"
  get "pages/tutors" => "pages#tutors"
  get "pages/kidscorner" => "pages#kidscorner"
  get "pages/contact" => "pages#contact"
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :lesson
  belongs_to :child
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :group, optional: true
  belongs_to :parent
end

app/models/group.rb
class Group < ApplicationRecord
	validates :tutor, presence: true
	# validates :schedule, presence: true
	belongs_to :tutor
	belongs_to :host, class_name: "Parent"
	attr_accessor :children
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :group, presence: true
  belongs_to :group
  attr_accessor :attendance
end

app/models/parent.rb
class Parent < User
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :parent
  attr_accessor :price, :num_credits
end

app/models/tutor.rb
class Tutor < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

	def show
		@admin = Admin.find(params[:id])
		require_user!(current_user == @admin)

        @activities = Activity.order(created_at: :desc)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :authenticate_user!
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController

	def index
		require_user!(admin_logged_in?)
		@tutors = Tutor.all
	end

	def show
		@tutor = Tutor.find(params[:id])
		require_user!(admin_logged_in? || current_user == @tutor)

		@groups = Group.where(tutor: @tutor)
	end

	def lessons
		@tutor = Tutor.find(params[:id])
		require_user!(admin_logged_in? || current_user == @tutor)

		@groups = Group.where(tutor: @tutor)

		query_res = Lesson.where(group: @groups).order(datetime: :desc)
		
		if query_res.count > 0
			@start = params[:search].present? && params[:search][:start_date].present? ? params[:search][:start_date] : query_res.last.datetime
			@end = params[:search].present? && params[:search][:end_date].present? ? params[:search][:end_date] : query_res.first.datetime
			@group = params[:search].present? && params[:search][:group].present? ? params[:search][:group] : @groups
		end

		@lessons = query_res.where(datetime: @start..@end, group: @group)
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/tutors/index.html.erb
<div class="page-header">
<h2>Tutors</h2>
<ul class="actions">
	<%= link_to "Back", admin_path(current_admin), class: "btn btn-primary" %>
</ul>
</div>

<div class="table-responsive">
<table class="table table-bordered">
	<thead>
		<td>Name</td>
		<td>Email</td>
		<td>Phone Number</td>
		<td>Address</td>
		<td></td>
		<td></td>
	</thead>
	<% @tutors.each do |tutor| %>
		<tr>
			<td><%= tutor.name %></td>
			<td><%= tutor.email %></td>
			<td><%= tutor.phone %></td>
			<td><%= address(tutor) %></td>
			<td><%= link_to "Lessons", tutor_lessons_path(tutor), class: "btn btn-primary" %></td>
			<td><%= link_to "View", tutor_path(tutor), class: "btn btn-primary" %></td>
		</tr>
	<% end %>
</table>
</div>

app/views/tutors/lessons.html.erb
<div class="page-header">
<h2><%= @tutor.name %>'s Lessons</h2>
<ul class="actions">
	<li><%= link_to "Back", tutor_path(@tutor), class: "btn btn-primary" %></li>
	<% if tutor_logged_in? && current_tutor == @tutor %>
		<li><%= link_to "New Lesson", new_lesson_path, class: "btn btn-success" %></li>
	<% end %>
</ul>
</div>

<%= form_for :search, method: :get do |f| %>
  <%= f.date_field :start_date, value: @start %>
  <%= f.date_field :end_date, value: @end %>
  <%= f.select :group, options_for_select(@groups.collect { |g| [g.name, g.id] }), prompt: "Group" %>
  <%= f.submit 'Filter', class: "btn btn-primary" %>
<% end %>

<br>

<div class="table-responsive">
<table class="table table-bordered">
	<thead>
		<td>Date and Time</td>
		<td>Group</td>
		<td>Notes</td>
		<td>Attendance</td>
	</thead>

	<% @lessons.each do |lesson| %>
		<tr>
			<td><%= lesson.datetime.strftime("%m/%d/%Y %l:%M %p") %></td>
			<td><%= lesson.group.name %></td>
			<td><%= lesson.notes %></td>
			<% attendance = Array.new %>
			<% Attendance.where(lesson: lesson).each do |a| %>
				<% child = "<span" + (a.present ? "" : " style='color: red;'") + ">" + a.child.name + "</span>" %>
				<% attendance.push(child) %>
			<% end %>
			<td><%= attendance.join(", ").html_safe %></td>
		</tr>
	<% end %>
</table>
</div>

app/views/tutors/schedule.html.erb
<h3>Weekly Schedule</h3>
<div class="table-responsive">
	<table class="table">
		<thead>
		<% Date::DAYNAMES.each do |day| %>
			<td><%= day %></td>
		<% end %>
		</thead>

		<% while @dow_slots.any? { |k, v| !v.empty? } do %>
		<tr>
			<% Date::DAYNAMES.each do |day| %>
				<% if @dow_slots[day].empty? %>
					<td></td>
				<% else %>
					<% slot = @dow_slots[day].slice!(0) %>
					<td>
						<div class="panel panel-primary slot">
							<div class="panel-heading">
								<%= slot[:datetime].strftime("%l:%M %p") %>
							</div>
							<div class="panel-body">
								<p>Group #<%= slot[:group].id %></p>
								<p><strong>Host Name:</strong><br>
								<%= slot[:group].host.name %></p>
								<p><strong>Phone:</strong><br>
								<%= slot[:group].host.phone %></p>
								<p><strong>Address:</strong><br>
								<%= address(slot[:group].host) %></p>
							</div>
						</div>
					</td>
				<% end %>
			<% end %>
		</tr>
		<% end %>
	</table>
</div>

app/views/tutors/show.html.erb
<div class="page-header">
<h2><%= @tutor.name %>'s Profile</h2>
<ul class="actions">
	<li><%= link_to "Lessons", tutor_lessons_path(@tutor), class: "btn btn-primary" %></li>
	<% if admin_logged_in? %>
		<li><%= link_to "Back", tutors_path, class: "btn btn-primary" %></li>
	<% end %>
</ul>
</div>

<br>

<p><strong>Phone:</strong> <%= @tutor.phone %></p>
<p><strong>Address:</strong> <%= address(@tutor) %></p>

<br>

<h3>Groups</h3>
<% group_count = @groups.count %>
<% ind = 0 %>
<% @groups.each do |group| %>
<% if ind % 4 == 0 %>
	<div class="row">
<% end %>
	<div class="col-sm-3">
		<div class="panel panel-default">
			<div class="panel-heading"><%= group.name %></div>
			<div class="panel-body">
				<p><strong>Children:</strong></p>
				<ul>
					<% Child.where(group_id: group.id).each do |child| %>
						<li>&#09;<%= link_to child.name, child_path(child) %></li>
					<% end %>
				</ul>

				<div class="well">
				<h4>Hosted By</h4>
					<p><strong>Name:</strong> <%= group.host.name %></p>
					<p><strong>Phone:</strong> <%= group.host.phone %></p>
					<p><strong>Address:</strong> <%= address(group.host) %></p>
				</div>
			</div>
		</div>
	</div>
<% if ind == group_count-1 or ind % 4 == 3 %>
	</div>
<% end %>
<% ind += 1 %>
<% end %>