config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  devise_for :admins, skip: [:registrations, :sessions]
  devise_for :parents, skip: :sessions, :controllers => {:registrations => "parent_registrations"}
  devise_for :tutors, skip: :sessions, :controllers => {:registrations => "tutor_registrations"}

  root :to => "pages#index"
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  get "groups/update_host", as: "update_host"
  resources :groups
  resources :children
  patch "children/:id/drop" => "children#drop", as: :drop

  resources :admins
  resources :parents
  get "parents/:id/payments" => "parents#payments", as: :parent_payments
  get "parents/:id/add_payment_info" => "parents#add_payment_info", as: :parent_add_payment_info
  post "parents/:id/store_card" => "parents#store_card", as: :parent_store_card
  resources :tutors
  get "tutors/:id/lessons" => "tutors#lessons", as: :tutor_lessons

  get "lessons/update_attendance", as: "update_attendance"
  resources :lessons

  get "pages/index" => "pages#index"
  get "pages/parents" => "pages#parents"
  get "pages/tutors" => "pages#tutors"
  get "pages/kidscorner" => "pages#kidscorner"
  get "pages/contact" => "pages#contact"
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :lesson
  belongs_to :child
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :group, optional: true
  belongs_to :parent
end

app/models/group.rb
class Group < ApplicationRecord
	validates :tutor, presence: true
	# validates :schedule, presence: true
	belongs_to :tutor
	belongs_to :host, class_name: "Parent"
	attr_accessor :children
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates :group, presence: true
  belongs_to :group
  attr_accessor :attendance
end

app/models/parent.rb
class Parent < User
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :parent
  attr_accessor :price, :num_credits
end

app/models/tutor.rb
class Tutor < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

	def show
		@admin = Admin.find(params[:id])
		require_user!(current_user == @admin)

        @activities = Activity.order(created_at: :desc)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :authenticate_user!
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
	skip_before_filter :verify_authenticity_token, :only => [:store_card]
	
	def index
		require_user!(admin_logged_in?)
		@parents = Parent.all
	end

	def show
		@parent = Parent.find(params[:id])
		require_user!(admin_logged_in? || current_user == @parent)

		@children = Child.where(parent: @parent)
	end

	def payments
		@parent = Parent.find(params[:id])
		require_user!(admin_logged_in? || (current_user == @parent && !@parent.customer_id.nil?))

		@children = Child.where(parent: @parent)

		query_res = Attendance.where(child: @children, present: true).sort do |a, b|
			b.lesson.datetime <=> a.lesson.datetime
		end

		if query_res.count > 0
			@start = params[:search].present? && params[:search][:start_date].present? ? params[:search][:start_date] : query_res.last.lesson.datetime
			@end = params[:search].present? && params[:search][:end_date].present? ? params[:search][:end_date] : query_res.first.lesson.datetime
		end

		@attendances = query_res.keep_if do |attendance|
			attendance.lesson.datetime >= @start && attendance.lesson.datetime <= @end
		end
	end

	def add_payment_info
		@parent = Parent.find(params[:id])
		require_user!(admin_logged_in? || current_user == @parent)
		@last4 = nil
		if !@parent.customer_id.nil?
			customer = Stripe::Customer.retrieve(@parent.customer_id)
			@last4 = Stripe::Source.retrieve(customer.default_source).card.last4
		end
	end

	def store_card
		@parent = Parent.find(params[:id])
		require_user!(admin_logged_in? || current_user == @parent)

		customer = Stripe::Customer.create(
			email: @parent.email,
			source: params[:stripeSource]
		)

		if @parent.update_attribute(:customer_id, customer.id)
			Activity.create!({activity_type: "UPDATE_CC", user: @parent})
			flash[:notice] = "Card successfully added!"
			redirect_to parent_path(@parent)
		else
			flash.now[:alert] = "Unable to add card!"
			render "add_payment_info"
		end
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/parents/add_payment_info.html.erb
<div class="page-header">
<h2><%= @parent.name %>'s Profile</h2>
	<ul class="actions">
		<li><%= link_to "Back", parent_path(@parent), class: "btn btn-primary" %></li>
	</ul>
</div>

<% if !@last4.nil? %>
	Stored Card: **** **** **** <%= @last4 %>
<% end %>

<%= form_tag parent_store_card_path(@parent), method: :post, authenticity_token: :true, id: "payment-form" do %>
	  <div class="form-row">
	    <label for="card-element">
	      Credit or debit card
	    </label>
	    <div id="card-element">
	      <!-- a Stripe Element will be inserted here. -->
	    </div>

	    <!-- Used to display Element errors -->
	    <div id="card-errors" role="alert"></div>
	  </div>

	  <button>Store Payment Info</button>
	<% end %>

	<script type="text/javascript">
	// Create a Stripe client
	var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

	// Create an instance of Elements
	var elements = stripe.elements();

	// Custom styling can be passed to options when creating an Element.
	// (Note that this demo uses a wider set of styles than the guide below.)
	var style = {
	  base: {
	    color: '#32325d',
	    lineHeight: '24px',
	    fontFamily: 'Helvetica Neue',
	    fontSmoothing: 'antialiased',
	    fontSize: '16px',
	    '::placeholder': {
	      color: '#aab7c4'
	    }
	  },
	  invalid: {
	    color: '#fa755a',
	    iconColor: '#fa755a'
	  }
	};

	// Create an instance of the card Element
	var card = elements.create('card', {style: style});

	// Add an instance of the card Element into the `card-element` <div>
	card.mount('#card-element');

	// Handle real-time validation errors from the card Element.
	card.addEventListener('change', function(event) {
	  const displayError = document.getElementById('card-errors');
	  if (event.error) {
	    displayError.textContent = event.error.message;
	  } else {
	    displayError.textContent = '';
	  }
	});

	var form = document.getElementById('payment-form');
	form.addEventListener('submit', function(event) {
	  	event.preventDefault();

	  	stripe.createSource(card).then(function(result) {
	    	if (result.error) {
	      		// Inform the user if there was an error
	      		var errorElement = document.getElementById('card-errors');
	      		errorElement.textContent = result.error.message;
	    	} else {
	      		// Send the source to your server
	      		stripeSourceHandler(result.source);
	    	}
	  	});

	  	function stripeSourceHandler(source) {
		  // Insert the source ID into the form so it gets submitted to the server
		  var form = document.getElementById('payment-form');
		  var hiddenInput = document.createElement('input');
		  hiddenInput.setAttribute('type', 'hidden');
		  hiddenInput.setAttribute('name', 'stripeSource');
		  hiddenInput.setAttribute('value', source.id);
		  form.appendChild(hiddenInput);

		  // Submit the form
		  form.submit();
		}
	});
	</script>

app/views/parents/index.html.erb
<div class="page-header">
<h2>Parents</h2>
<ul class="actions">
	<%= link_to "Back", admin_url(current_admin), class: "btn btn-primary" %>
</ul>
</div>

<div class="table-responsive">
<table class="table table-bordered">
	<thead>
		<td>Name</td>
		<td>Email</td>
		<td>Phone Number</td>
		<td>Address</td>
		<td></td>
		<td></td>
	</thead>
	<% @parents.each do |parent| %>
		<tr>
			<td><%= parent.name %></td>
			<td><%= parent.email %></td>
			<td><%= parent.phone %></td>
			<td><%= address(parent) %></td>
			<td><%= link_to "Payments", parent_payments_path(parent), class: "btn btn-primary" %></td>
			<td><%= link_to "View", parent_path(parent), class: "btn btn-primary" %></td>
		</tr>
	<% end %>
</table>
</div>

app/views/parents/payments.html.erb
<div class="page-header">
<h2><%= @parent.name %>'s Payments</h2>
<ul class="actions">
	<li><%= link_to "Back", parent_path(@parent), class: "btn btn-primary" %></li>
</ul>
</div>

<%= form_for :search, method: :get do |f| %>
  <%= f.date_field :start_date, value: @start %>
  <%= f.date_field :end_date, value: @end %>
  <%= f.submit 'Filter', class: "btn btn-primary" %>
<% end %>

<br>

<div class="table-responsive">
<table class="table table-bordered">
	<thead>
		<td>Date and Time</td>
		<td>Group</td>
		<td>Child</td>
		<td>Payment Amount</td>
	</thead>

	<% @attendances.each do |attendance| %>
		<tr>
			<td><%= attendance.lesson.datetime.strftime("%m/%d/%Y %l:%M %p") %></td>
			<td><%= attendance.lesson.group.name %></td>
			<td><%= attendance.child.name %></td>
			<td><%= number_to_currency(attendance.lesson.price) %></td>
		</tr>
	<% end %>
</table>
</div>

app/views/parents/show.html.erb
<div class="page-header">
<h2><%= @parent.name %>'s Profile</h2>
	<ul class="actions">
		<% if @parent.customer_id.nil? %>
			<li><%= link_to "Add Credit Card", parent_add_payment_info_path(@parent), class: "btn btn-success" %></li>
		<% else %>
			<li><%= link_to "Update Credit Card", parent_add_payment_info_path(@parent), class: "btn btn-warning" %></li>
		<% end %>
		<% if parent_logged_in? && current_parent == @parent && !@parent.customer_id.nil? %>
			<li><%= link_to "Payments", parent_payments_path(@parent), class: "btn btn-primary" %></li>
			<li><%= link_to "Add Child", new_child_path, class: "btn btn-success" %></li>
		<% end %>
		<% if admin_logged_in? %>
			<li><%= link_to "Back", parents_path, class: "btn btn-primary" %></li>
		<% end %>
	</ul>
</div>

	<% if @parent.customer_id.nil? %>
		Please enter your payment info to access all functions.
	<% else %>
		<p><strong>Phone:</strong> <%= @parent.phone %></p>
		<p><strong>Address:</strong> <%= address(@parent) %></p>

		<br>

		<h3>Children</h3>
		<% child_count = @children.count %>
		<% ind = 0 %>
		<% @children.each do |child| %>
		<% if ind % 4 == 0 %>
			<div class="row">
		<% end %>
			<div class="col-sm-3">
				<div class="panel panel-default">
					<div class="panel-heading">
						<%= child.name %>
						<%= link_to "View", child_path(child), class: "btn btn-primary" %>
					</div>
					<div class="panel-body">
						<% if child.group.nil? %>
							<p>Group Unassigned</p>
						<% else %>
							<p>Group: <%= child.group.name %></p>
							<p>Price: <%= number_to_currency(child.group.price) %></p>
							<p>Tutor: <%= link_to child.group.tutor.name, tutor_path(child.group.tutor) %></p>
							<div class="well">
								<h4>Hosted By</h4>
								<p><strong>Name:</strong> <%= child.group.host.name %></p>
								<p><strong>Phone:</strong> <%= child.group.host.phone %></p>
								<p><strong>Address:</strong> <%= address(child.group.host) %></p>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		<% if ind == child_count-1 or ind % 4 == 3 %>
			</div>
		<% end %>
		<% ind += 1 %>
		<% end %>
	<% end %>